import "dotenv/config";
import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import * as schema from "@/db/schema";
const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql, { schema });
const main = async () => {
  try {
    console.log("Seeding database");
    await Promise.all([
      db.delete(schema.userProgress),
      db.delete(schema.challenges),
      db.delete(schema.units),
      db.delete(schema.lessons),
      db.delete(schema.courses),
      db.delete(schema.challengeOptions),
      db.delete(schema.userSubscription),
    ]);

    const courses = await db
      .insert(schema.courses)
      .values([
        { id: 1, title: "Tiếng Anh", imageSrc: "/EN - English.svg" },
        { id: 2, title: "Tiếng Pháp", imageSrc: "/fr.svg" },
        { id: 3, title: "Tiếng Hàn", imageSrc: "/KR - Korea (South).svg" },
        { id: 4, title: "Tiếng Nhật", imageSrc: "/jp.svg" },
      ])
      .returning();
    await db.insert(schema.units).values([
      {
        id: 1,
        courseId: 1,
        title: "Chương 1",
        description: "Gọi Đồ Ăn , Đồ Uống",
        order: 1,
      },
      {
        id: 2,
        courseId: 1,
        title: "Chương 2",
        description: "Giới Thiệu Bản Thân",
        order: 2,
      },
    ]);

    await db.insert(schema.lessons).values([
      {
        id: 1,
        unitId: 1,
        order: 1,
        title: "Danh Từ",
      },
      {
        id: 2,
        unitId: 1,
        order: 2,
        title: "Động Từ",
      },
      {
        id: 3,
        unitId: 1,
        order: 3,
        title: "Động Từ",
      },
      {
        id: 4,
        unitId: 1,
        order: 4,
        title: "Động Từ",
      },
      {
        id: 5,
        unitId: 1,
        order: 5,
        title: "Động Từ",
      },
      {
        id: 6,
        unitId: 2,
        order: 6,
        title: "Danh Từ",
      },
      {
        id: 7,
        unitId: 2,
        order: 7,
        title: "Động Từ",
      },
      {
        id: 8,
        unitId: 2,
        order: 8,
        title: "Động Từ",
      },
      {
        id: 9,
        unitId: 2,
        order: 9,
        title: "Động Từ",
      },
      {
        id: 10,
        unitId: 2,
        order: 10,
        title: "Động Từ",
      },
    ]);
    await db.insert(schema.challenges).values([
      {
        id: 1,
        lessonId: 1,
        type: "SELECT",
        order: 1,
        question: "Từ nào dưới đây là sữa",
      },
      {
        id: 2,
        lessonId: 1,
        type: "SELECT",
        order: 2,
        question: "Từ nào dưới đây là trà",
      },
      {
        id: 3,
        lessonId: 1,
        type: "ASSIST",
        order: 3,
        question: "Từ nào dưới đây là cà phê",
      },
      {
        id: 4,
        lessonId: 2,
        type: "SELECT",
        order: 1,
        question: "Từ nào dưới đây là sữa",
      },
      {
        id: 5,
        lessonId: 2,
        type: "SELECT",
        order: 2,
        question: "Từ nào dưới đây là trà",
      },
      {
        id: 6,
        lessonId: 2,
        type: "ASSIST",
        order: 3,
        question: "Từ nào dưới đây là cà phê",
      },
      {
        id: 7,
        lessonId: 3,
        type: "SELECT",
        order: 1,
        question: "Từ nào dưới đây là sữa",
      },
      {
        id: 8,
        lessonId: 3,
        type: "SELECT",
        order: 2,
        question: "Từ nào dưới đây là trà",
      },
      {
        id: 9,
        lessonId: 3,
        type: "ASSIST",
        order: 3,
        question: "Từ nào dưới đây là cà phê",
      },
      {
        id: 10,
        lessonId: 4,
        type: "SELECT",
        order: 1,
        question: "Từ nào dưới đây là sữa",
      },
      {
        id: 11,
        lessonId: 4,
        type: "SELECT",
        order: 2,
        question: "Từ nào dưới đây là trà",
      },
      {
        id: 12,
        lessonId: 4,
        type: "ASSIST",
        order: 3,
        question: "Từ nào dưới đây là cà phê",
      },
      {
        id: 13,
        lessonId: 5,
        type: "SELECT",
        order: 1,
        question: "Từ nào dưới đây là sữa",
      },
      {
        id: 14,
        lessonId: 5,
        type: "SELECT",
        order: 2,
        question: "Từ nào dưới đây là trà",
      },
      {
        id: 15,
        lessonId: 5,
        type: "ASSIST",
        order: 3,
        question: "Từ nào dưới đây là cà phê",
      },
      {
        id: 16,
        lessonId: 6,
        type: "SELECT",
        order: 1,
        question: "Từ nào dưới đây là sữa",
      },
      {
        id: 17,
        lessonId: 6,
        type: "SELECT",
        order: 2,
        question: "Từ nào dưới đây là trà",
      },
      {
        id: 18,
        lessonId: 6,
        type: "ASSIST",
        order: 3,
        question: "Từ nào dưới đây là cà phê",
      },
      {
        id: 19,
        lessonId: 7,
        type: "SELECT",
        order: 1,
        question: "Từ nào dưới đây là sữa",
      },
      {
        id: 20,
        lessonId: 7,
        type: "SELECT",
        order: 2,
        question: "Từ nào dưới đây là trà",
      },
      {
        id: 21,
        lessonId: 7,
        type: "ASSIST",
        order: 3,
        question: "Từ nào dưới đây là cà phê",
      },
      
    ]);
    await db.insert(schema.challengeOptions).values([
      {
        id: 1,
        challengeId: 1,
        imageSrc: "/milk.svg",
        correct: true,
        text: "Milk",
        audioSrc: "/en_milk.mp3",
      },
      {
        id: 2,
        challengeId: 1,
        imageSrc: "/water.svg",
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 3,
        challengeId: 1,
        imageSrc: "/tea.svg",
        correct: false,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 4,
        challengeId: 2,
        imageSrc: "/milk.svg",
        correct: false,
        text: "Milk",
        audioSrc: "/en_milk.mp3",
      },
      {
        id: 5,
        challengeId: 2,
        imageSrc: "/water.svg",
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 6,
        challengeId: 2,
        imageSrc: "/tea.svg",
        correct: true,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 7,
        challengeId: 3,
        correct: true,
        text: "Coffee",
        audioSrc: "/en_coffee.mp3",
      },
      {
        id: 8,
        challengeId: 3,
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 9,
        challengeId:3,
        correct: false,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 10,
        challengeId: 4,
        imageSrc: "/milk.svg",
        correct: true,
        text: "Milk",
        audioSrc: "/en_milk.mp3",
      },
      {
        id: 11,
        challengeId: 4,
        imageSrc: "/water.svg",
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 12,
        challengeId: 4,
        imageSrc: "/tea.svg",
        correct: false,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 13,
        challengeId: 5,
        imageSrc: "/milk.svg",
        correct: false,
        text: "Milk",
        audioSrc: "/en_milk.mp3",
      },
      {
        id: 14,
        challengeId: 5,
        imageSrc: "/water.svg",
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 15,
        challengeId: 5,
        imageSrc: "/tea.svg",
        correct: true,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 16,
        challengeId: 6,
        correct: true,
        text: "Coffee",
        audioSrc: "/en_coffee.mp3",
      },
      {
        id: 17,
        challengeId: 6,
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 18,
        challengeId:6,
        correct: false,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 19,
        challengeId: 7,
        imageSrc: "/milk.svg",
        correct: true,
        text: "Milk",
        audioSrc: "/en_milk.mp3",
      },
      {
        id: 20,
        challengeId: 7,
        imageSrc: "/water.svg",
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 21,
        challengeId: 7,
        imageSrc: "/tea.svg",
        correct: false,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 22,
        challengeId: 8,
        imageSrc: "/milk.svg",
        correct: false,
        text: "Milk",
        audioSrc: "/en_milk.mp3",
      },
      {
        id: 23,
        challengeId: 8,
        imageSrc: "/water.svg",
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 24,
        challengeId: 8,
        imageSrc: "/tea.svg",
        correct: true,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 25,
        challengeId: 9,
        correct: true,
        text: "Coffee",
        audioSrc: "/en_coffee.mp3",
      },
      {
        id: 26,
        challengeId: 9,
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 27,
        challengeId:9,
        correct: false,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 28,
        challengeId: 16,
        imageSrc: "/water.svg",
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 29,
        challengeId: 16,
        imageSrc: "/milk.svg",
        correct: true,
        text: "Milk",
        audioSrc: "/en_milk.mp3",
      },
      {
        id: 30,
        challengeId: 16,
        imageSrc: "/tea.svg",
        correct: false,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 31,
        challengeId: 17,
        imageSrc: "/milk.svg",
        correct: false,
        text: "Milk",
        audioSrc: "/en_milk.mp3",
      },
      {
        id: 32,
        challengeId: 17,
        imageSrc: "/water.svg",
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id:33,
        challengeId: 17,
        imageSrc: "/tea.svg",
        correct: true,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
      {
        id: 34,
        challengeId: 18,
        correct: true,
        text: "Coffee",
        audioSrc: "/en_coffee.mp3",
      },
      {
        id: 35,
        challengeId: 18,
        correct: false,
        text: "Water",
        audioSrc: "/en_water.mp3",
      },
      {
        id: 36,
        challengeId:18,
        correct: false,
        text: "Tea",
        audioSrc: "/en_tea.mp3",
      },
    ]);

    console.log("Seeding finished");
  } catch (error) {
    console.error(error);
    throw new Error("Fail to seed the database");
  }
};
void main();
